//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json;

namespace WebSeviceBancDelTemps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Id_Report { get; set; }
        public string description { get; set; }
        public bool is_revised { get; set; }
        public int Post_Id_Post { get; set; }
        public int Id_Reporter { get; set; }
        public int Id_Reported { get; set; }
        [JsonIgnore]
        public virtual Post Post { get; set; }
    }
}
